### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Qodestackr** [codeInn001/image-gallery#1]
Hey, I couldn't get a better way to communicate with you since I have no setting yet to edit your PR.

[I have this attached ](https://github.com/Qodestackr/Astro-Review) for your reference. Astro is in beta and will be changing a lot.

Sorry makes no sense having this issue on this repo. @codeInn001 

Feel free to clone it and test it.

**Comment by codeInn001** [comment]
@Qodestackr sure I will clone it. Thanks.

Concerning the issue, no problem.
Should I update my article with what you have in the link above.

**Comment by Qodestackr** [comment]
No Don't include the Link. In your conclusion, make sure to mention that Astro is still in beta and it can change without warning..

**Comment by codeInn001** [comment]
> No Don't include the Link. In your conclusion, make sure to mention that Astro is still in beta and it can change without warning..

Okay, boss. let's connect on Twitter. send your username.

has hector assigned you to review my article.

**Comment by codeInn001** [comment]
can i use [this](https://github.com/codeInn001/Astro-Review) as the link to my source code

**Comment by Qodestackr** [comment]
😂😂😂Why fork?

**Comment by codeInn001** [comment]
> 😂😂😂Why fork?

So that I can use it as a link to the article.🙃🙃

**Comment by Qodestackr** [comment]
Okay. The `npm init astro` does not generate a file named layouts. Could you kindly remove it so that the content moderators can let me proceed for a final review?
@codeInn001 besides we are not even using it.

Done boss. Thanks.

**Comment by codeInn001** [comment]
@Qodestackr Whatsup bro
